package com.maz.springboot3example.domain;

public enum ResourceType {
    SINGLE, DOUBLE, STUDIO, DELUXE, SUITE, PRESIDENTIAL_SUITE,
    SINGLE_WITH_VIEW, DOUBLE_WITH_VIEW, STUDIO_WITH_VIEW, DELUXE_WITH_VIEW, SUITE_WITH_VIEW, PRESIDENTIAL_WITH_VIEW
}
